trigger:
- dev # Change this to the branch you want to trigger the pipeline from

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: Build
  jobs:
  - job: BuildJob
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: UsePythonVersion@0 # Use this task to select the Python version
      inputs:
        versionSpec: '3.11'
    - script: | # Use this script to install dependencies
        python -m venv venv
        source venv/bin/activate
        pip install -r requirements.txt
      displayName: 'Install Dependencies'
    - task: ArchiveFiles@2
      inputs:
        rootFolderOrFile: '$(Build.SourcesDirectory)'
        archiveType: 'zip'
        archiveFile: '$(Build.ArtifactStagingDirectory)/helloworld_app.zip'
        includeRootFolder: false
    - task: PublishBuildArtifacts@1 # Publish the build artifacts
      inputs:
        pathToPublish: '$(Build.ArtifactStagingDirectory)/helloworld_app.zip'
        artifactName: 'app'

- stage: Deploy
  jobs:
  - job: DeployJob
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: DownloadBuildArtifacts@1
      inputs:
        buildType: 'current' # Download the current build artifacts
        downloadType: 'single' 
        artifactName: 'app'
        downloadPath: '$(System.ArtifactsDirectory)/artifact' # Specify the download path

    - script: |
        echo "List all files"
        tree $(System.ArtifactsDirectory)/artifact/
      displayName: "List Extracted Files"

    - task: AzureWebApp@1 # Deploy the app to Azure Web App
      inputs:
        azureSubscription: 'STRATUS' # Change this to your Service Connection
        appName: 'azwebapp' # Azure Web App name
        package: '$(System.ArtifactsDirectory)/artifact/app/helloworld_app.zip'